spring.application.name=miapp

# Conexión a PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mrx_db_jygs}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mrx_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tu_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Desactivar la ejecución de scripts para evitar errores en Render
spring.sql.init.mode=never