spring.application.name=miapp

# Conexión a PostgreSQL (Render usará las variables de entorno si existen, si no caerá en PostgreSQL local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mrx_db_jygs}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mrx_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tu_password}
spring.datasource.driver-class-name=org.postgresql.Driver
s
# Inicialización del script schema.sql
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true