spring.application.name=miapp
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/mrx;AUTO_SERVER=TRUE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.sql.init.mode=always
