CREATE TABLE IF NOT EXISTS cobros (
    id VARCHAR(36) PRIMARY KEY,
    folio VARCHAR(100) NOT NULL UNIQUE,
    cliente VARCHAR(200) NOT NULL,
    motocicleta VARCHAR(200) NOT NULL,
    placas VARCHAR(50) NOT NULL,
    servicio_solicitado VARCHAR(500) NOT NULL,
    servicio_realizado VARCHAR(500) NOT NULL,
    mecanico VARCHAR(200) NOT NULL,
    fecha_pago BIGINT NOT NULL,
    mano_obra DECIMAL(12, 2) NOT NULL,
    servicio_extra_descripcion VARCHAR(500),
    servicio_extra_precio DECIMAL(12, 2) NOT NULL,
    subtotal DECIMAL(12, 2) NOT NULL,
    iva DECIMAL(12, 2) NOT NULL,
    total DECIMAL(12, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS cobro_refacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cobro_id VARCHAR(36) NOT NULL,
    sku VARCHAR(100) NOT NULL,
    nombre VARCHAR(300) NOT NULL,
    precio_unitario DECIMAL(12, 2) NOT NULL,
    cantidad INTEGER NOT NULL,
    importe DECIMAL(12, 2) NOT NULL,
    CONSTRAINT fk_cobro_refacciones_cobro
        FOREIGN KEY (cobro_id) REFERENCES cobros(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cobros_fecha_pago ON cobros(fecha_pago);